### ISSUE TITLE
Using the /search/ API to search by MARC 21 codes

### ISSUE THREAD

**Issue by UromPLAt** [LibraryOfCongress/data-exploration#35]
Hi guys,
Is that possible?

Talking about this: https://libraryofcongress.github.io/data-exploration/requests.html#searching
From the GUI, I can generate queries like this: 650A Computer AND 650A networks NOT K650 Neural NOT 650V Congresses

Searching MARC 21 tags directly.

**Comment by ptrourke** [comment]
Sorry, this issue was missed. Can you provide a URL with the query you're talking about so I can test? When I try the same query in the search box, I'm not getting any results. I suspect you're querying catalog.loc.gov, which isn't accessible through the loc.gov API, but rather through the Z39.50 SRU interface (https://www.loc.gov/z3950/lcserver.html).

**Comment by UromPLAt** [comment]
I guess so, but this was so long ago that I don't remember what I was running.
I'll close this, thanks!
